# Generated by Django 4.2.3 on 2023-07-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_saytome'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgFromAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mymsg', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
